services:
  - type: web
    name: notespace
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
